version: "3.8"

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    restart: unless-stopped
    ports:
      - "8096:8096"
    volumes:
      - /mnt/media/docker/appdata/jellyfin/config:/config
      - /mnt/media/docker/appdata/jellyfin/cache:/cache
      - /mnt/media:/media

    environment:
      - TZ=Europe/Madrid
