version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:2026.04.1
    hostname: pihole
    network_mode: "host"
    environment:
      TZ: "Europe/Madrid"
      WEBPASSWORD: ${pihole_password}
      DNSMASQ_LISTENING: "all"
      DNS1: 1.1.1.1
      DNS2: 1.0.0.1
    volumes:
      - /mnt/media/docker/appdata/pihole/pihole:/etc/pihole
      - /mnt/media/docker/appdata/pihole/dnsmasq.d:/etc/dnsmasq.d
    restart: unless-stopped
